name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Or your main branch name

permissions:
  contents: read
  pages: write
  id-token: write
  checks: write
  actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Apply patch to whisper.cpp
        working-directory: whisper.cpp
        run: git apply ../whisper.patch
      - name: Add release key
        run: base64 -d <<< "$MY_RELEASE_KEY" > app/my-release-key.jks
        env:
          MY_RELEASE_KEY: ${{ secrets.MY_RELEASE_KEY }}

      - name: Setup Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Or your desired JDKversion
          distribution: 'temurin'
      #- name: Tests
      #  run: ./gradlew allTests -x wasmJsBrowserTest
      #- name: Test Report
      #  uses: dorny/test-reporter@v1
      #  if: success() || failure()    # run this step even if previous step failed
      #  with:
      #    name: Test Results
      #    path: composeApp/build/test-results/**/*.xml
      #    reporter: java-junit
      - name: Build app
        run: VERSION_CODE=$GITHUB_RUN_NUMBER VERSION_NAME=$(git rev-parse --short HEAD)  ./gradlew assemble
      - name: Build Android app bundle
        run: VERSION_CODE=$GITHUB_RUN_NUMBER VERSION_NAME=$(git rev-parse --short HEAD)  ./gradlew bundle
      - name: Publish app
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: eu.schmitthenner.transcribe
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: draft
      - name: Publish app bundle artefact
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: |
            app/build/outputs/bundle/release/app-release.aab
            app/build/outputs/apk/release/app-release.apk
      - name: Upload website artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: app/build/outputs
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

