name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ] # Or your main branch name

permissions:
  contents: read
  pages: write
  id-token: write
  checks: write
  actions: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Apply patch to whisper.cpp
        working-directory: whisper.cpp
        run: git apply ../whisper.patch
      - name: Setup Gradle Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts', '**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21' # Or your desired JDKversion
          distribution: 'temurin'
      #- name: Tests
      #  run: ./gradlew allTests -x wasmJsBrowserTest
      #- name: Test Report
      #  uses: dorny/test-reporter@v1
      #  if: success() || failure()    # run this step even if previous step failed
      #  with:
      #    name: Test Results
      #    path: composeApp/build/test-results/**/*.xml
      #    reporter: java-junit
      - name: Build app
        run: ./gradlew assemble
      - name: Build Android app bundle
        run: ./gradlew bundle
      - name: Publish app bundle artefact
        uses: actions/upload-artifact@v4
        with:
          name: bundle
          path: |
            app/build/outputs/bundle/release/app-release.aab
            app/build/outputs/apk/release/app-release.apk